### ISSUE TITLE
Allow underscore in task list to denote unchecked item

### ISSUE THREAD

**Issue by hex4badass** [jgm/djot#305]
> Thank you for djot and CommonMark

Currently, unchecked item requires exactly one space inside square brackets.
It leads to typing errors, especially in editors without monospaced fonts,
for example, some apps on phones.

This issue was encountered when using markdown, but it also applies to djot.
Also, when writing this issue on GitHub from the browser, the text box does not
use monospaced fonts.

Therefore, allow underscore in task list to denote unchecked item.

Why underscore?\
Because the unchecked box will look like an empty box in the source code.

Take a look at the following example:

```
- [_] unchecked item with underscore
- [ ] unchecked item with space
- [x] checked item with lowercase letter x
- [X] checked item with uppercase letter X
```

**Comment by jgm** [comment]
I like the idea.

**Comment by hex4badass** [comment]
Thank you!

**Comment by dereuromark** [comment]
I also like it. Any reasons not to implement and adjust the specs and reference implementation on this one?

  1. It's additive (doesn't break existing [ ] syntax)                                                                           
  1. Simple to implement - just extend the parser to accept _ as equivalent to space                                             
       
I made a demo implementation for PHP: https://github.com/php-collective/djot-php/pull/87
